apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pet-battle-api-i6o3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pet-battle-api-i6o3
    app.kubernetes.io/part-of: petbattle-api
  name: pet-battle-api-i6o3
  namespace: ckavili1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: pet-battle-api-i6o3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: pet-battle-api-i6o3
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:4c56ed014e7688b7d74ed94ce62ec9682dde8f2822ac707ebbe66e5b832a35f4
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
