apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pet-battle-api-i6o3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pet-battle-api-i6o3
    app.kubernetes.io/part-of: petbattle-api
  name: pet-battle-api-i6o3
  namespace: ckavili1-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: pet-battle-api-i6o3
    weight: null
status: {}
