apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pet-battle-api-i6o3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pet-battle-api-i6o3
    app.kubernetes.io/part-of: petbattle-api
  name: pet-battle-api-i6o3
  namespace: ckavili1-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: pet-battle-api-i6o3
status:
  loadBalancer: {}
